[project]
name = "url-to-web-content"
version = "0.0.1"
description = "URL to Web Content"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "playwright>=1.52.0",
]
